version: '3.8'

services:
  app:
    build:
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/var/www:delegated
    container_name: app
    restart: unless-stopped
    tty: true
    ports:
      - "9000"
    command:
      - "php-fpm"
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      APP_DEBUG: 1
      APP_ENV: local
    working_dir: /var/www
    networks:
      - temper-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - temper-network

#Docker Networks
networks:
  temper-network:
    driver: bridge

